Recepies/Recepies/Controllers/AboutSiteController.cs
using Recepies.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Recepies.Controllers
{
    public class AboutSiteController : Controller
    {
        // GET: AboutSite
        public ActionResult Index()
        {
            var currentUser = ((User)HttpContext.Session["user"]);
            if (currentUser != null)
            {
                return View();
            }
            return RedirectToAction("Index", "Error");            
        }

        public string GetAboutSiteText()
        {
            var text = System.IO.File.ReadAllText(Server.MapPath("\\Content\\TextFiles\\AboutSite.txt"));
            return text;
        }
    }
}

Recepies/Recepies/Controllers/StatsController.cs
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using Recepies.Models;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Reflection;
using System.Web;
using System.Web.Mvc;

namespace Recepies.Controllers
{
    public class StatsController : Controller
    {
        private DbContext db = new DbContext(); 

        // GET: Stats
        public ActionResult Stats()
        {
            if (((User)HttpContext.Session["user"]) != null)
            {
                var difficulties = db.Recipies.GroupBy(r => r.Difficulty).Select(g => new { difficulty = ((Difficulty)g.Key).ToString(), count = g.Count() }).ToList();
                var difficultiesData = JsonConvert.SerializeObject(difficulties);
                ViewBag.difficulties = difficultiesData;

                var users = db.Recipies.GroupBy(r => r.User).Select(i => new { name = ((User)i.Key).FullName, recipies = i.Count() });
                var usersData = JsonConvert.SerializeObject(users);
                ViewBag.users = usersData;

                return View();
            }

            return RedirectToAction("Index", "Error");
        }

      
    }
}

Recepies/Recepies/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Carine Goren</title>
    <link href="~/Content/bootstrap.css" rel="stylesheet" />
    <link href="~/Content/recipies.css" rel="stylesheet" />
    <link href="vendor/font-awesome/css/font-awesome.min.css" rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700" rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/css?family=Lato:400,700,400italic,700italic" rel="stylesheet" type="text/css">
    <script src="~/Scripts/jquery-1.10.2.js"></script>
    <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
    <script>
        $(function () {
            $("#dialog").dialog({
                autoOpen: false,
                show: {
                    effect: "blind",
                    duration: 1000
                },
                hide: {
                    effect: "explode",
                    duration: 1000
                }
            });

            $("#help").on("click", function () {
                $("#dialog").dialog("open");
            });
        });
    </script>
</head>

<body>
    <!-- Navigation -->
    <nav id="mainNav" class="navbar navbar-default navbar-fixed-top navbar-custom">
        <div class="container">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header page-scroll">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span> Menu <i class="fa fa-bars"></i>
                </button>
                <a class="navbar-brand" href="/Users?Length=8">Carine Goren</a>
            </div>
            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav navbar-right">
                    <li class="hidden">
                        <a href="#page-top"></a>
                    </li>
                    @{var sessionVar = (Recepies.Models.User)HttpContext.Current.Session["user"];
                        if (sessionVar != null)
                        {
                            <li class="page-scroll">
                                @Html.ActionLink("About", "Index", "AboutSite")
                            </li>
                            <li class="page-scroll">
                                @Html.ActionLink("Ingredients", "Index", "Ingredients")
                            </li>
                            <li class="page-scroll">
                                @Html.ActionLink("Recipies", "Index", "Recipies")
                            </li>
                            <li class="page-scroll">
                                @Html.ActionLink("Statistics", "Stats", "Stats")
                            </li>
                            <li class="page-scroll">
                                @Html.ActionLink("Users", "Index", "Users")
                            </li>
                            <li>
                                @Html.ActionLink("LogOff", "Logoff", "Users", routeValues: null, htmlAttributes: new { id = "logoutLink" })
                            </li>
                        }
                        else
                        {
                            <li class="page-scroll">
                                @Html.ActionLink("Register", "Register", "Users", routeValues: null, htmlAttributes: new { id = "registerLink" })
                            </li>
                            <li>
                                @Html.ActionLink("Login", "Login", "Users", routeValues: null, htmlAttributes: new { id = "loginLink" })
                            </li>
                        } }
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container-fluid -->
    </nav>

    <!-- Header -->
    <header>
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <div class="intro-text">
                        <span class="name">Carine Goren</span>
                        <span class="skills">Best things in life are SWEET</span>
                    </div>
                </div>
            </div>
        </div>
    </header>

    <section id="portfolio">
        <div class="container">
            @RenderBody()
        </div>
    </section>

    <footer class="text-center">
        <div class="footer-below">
            <div class="container">
                <div class="row">
                    <div class="col-lg-12">
                        Copyright &copy; @DateTime.Now.Year - Carine Goren web site
                    </div>
                </div>
            </div>
        </div>
    </footer>

    @RenderSection("scripts", required: false)
</body>
</html>