Recepies/Recepies/Controllers/RecipiesController.cs
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web.Mvc;
using Recepies.Models;
using DbContext = Recepies.Models.DbContext;
using System.ComponentModel.DataAnnotations;
using System.Collections.Generic;
using System.Threading.Tasks;
using Recepies.Common;

namespace Recepies.Controllers
{
    public class RecipiesController : Controller
    {
        public class CreateRecipieViewModel
        {
            public CreateRecipieViewModel()
            {
                // Init the array for the case of no ingredients selected
                IngredientsIds = new List<int>();
            }
            public Recipe Recipe { get; set; }

            public List<int> IngredientsIds { get; set; }
        }


        private DbContext db = new DbContext();

        // GET: Recipies
        public ActionResult Index()
        {
            var currentUser = ((User)HttpContext.Session["user"]);
            if (currentUser != null)
            {
               return View(db.Recipies.Include(r => r.User).ToList());
            }
            
            return RedirectToAction("Index", "Error");

        }

        // GET: Recipies/Search
        public ActionResult Search(string ingredient = null, string user = null, string level = null)
        {
            ViewBag.Ingredients = new SelectList(db.Ingredients.Select(i => i.Name));
            if (((User)HttpContext.Session["user"]) != null)
            {
                var returnDataQurey = db.Recipies.Include(r => r.User).Select(r => r);

                if (!string.IsNullOrEmpty(ingredient))
                {
                    returnDataQurey = returnDataQurey.Where(r => r.Ingredients.Any(i => i.Name == ingredient));
                }

                if (!string.IsNullOrEmpty(user))
                {
                    returnDataQurey = returnDataQurey.Where(r => r.User.FullName.Contains(user));
                }

                if (!string.IsNullOrEmpty(level))
                {
                    returnDataQurey = returnDataQurey.Where(r => ((int)r.Difficulty).ToString() == level);
                }

                return View(returnDataQurey.ToList());
            }
            else
            {
                return RedirectToAction("Index", "Error");
            }
        }

        // GET: Recipies/Details/5 OR recommended recipe
        public ActionResult Details(int? id)
        {
            Recipe recipe = null;

            if (id == null)
            {
                return RedirectToAction("Index", "Error");
            }
            // Checks if asked for recommendation
            else if (id == -999)
            {
                var currentUser = ((User)HttpContext.Session["user"]);

                // Finds the current user's highest difficuly level recipe 
                Difficulty highestDifficultyPerUser = (db.Recipies.Where(r => r.User.Id == currentUser.Id)
                                                                  .OrderBy(r => r.Difficulty))
                                                                  .First().Difficulty;

                // Finds recommended recipe made by other user AND as difficult (or more) as the user can make
                recipe = db.Recipies.Where(r => r.User.Id != currentUser.Id)
                                    .Where(r => r.Difficulty <= highestDifficultyPerUser)
                                    .Include(r => r.Ingredients)
                                    .Include(r => r.User)
                                    .FirstOrDefault();
            }
            else
            {
                recipe = db.Recipies.Where(r => r.Id == id.Value).Include(r => r.Ingredients).Include(r => r.User).FirstOrDefault();
            }


            if (recipe == null)
            {
                return HttpNotFound();
            }

            return View(recipe);
        }

        // GET: Recipies/Create
        public ActionResult Create()
        {
            var ingredientList = new MultiSelectList(db.Ingredients.Select(i => i), "Id", "Name");
            ViewBag.Ingredients = ingredientList;
            if (((User)HttpContext.Session["user"]) != null)
            {
                return View();
            }
            else
            {
                return RedirectToAction("Index", "Error");
            }
        }

        // POST: Recipies/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Recipe, IngredientsIds")] CreateRecipieViewModel viewModel)
        {
            if (ModelState.IsValid)
            {
                // Add the selected Ingredients
                viewModel.Recipe.Ingredients = new List<Ingredient>();
                foreach (var ingredientId in viewModel.IngredientsIds)
                {
                    var ingredientToAdd = db.Ingredients.Find(ingredientId);
                    viewModel.Recipe.Ingredients.Add(ingredientToAdd);
                }

                // Set the current user as the owner of the recipe
                // Find - To avoid creating new user with the same name
                var owner = db.Users.Find(((User)HttpContext.Session["user"]).Id);
                viewModel.Recipe.User = owner;

                db.Recipies.Add(viewModel.Recipe);
                db.SaveChanges();
                PostToTwitterAsync("Check out the new recipe added to Carine Goren website! http://localhost:55527/Recipies/Details/" + viewModel.Recipe.Id);
                return RedirectToAction("Index");
            }

            return View(viewModel);
        }

        // GET: Recipies/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return RedirectToAction("Index", "Error");
            }
            Recipe recipe = db.Recipies.Where(r => r.Id == id).Include(r => r.User).FirstOrDefault();
            if (recipe == null)
            {
                return HttpNotFound();
            }
            return View(recipe);
        }

        // POST: Recipies/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Name,Difficulty,PreparationTimeInMinutes,Context")] Recipe recipe)
        {
            if (ModelState.IsValid)
            {
                db.Entry(recipe).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(recipe);
        }

        // GET: Recipies/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return RedirectToAction("Index", "Error");
            }
            Recipe recipe = db.Recipies.Include(r => r.User).Where(r => r.Id == id).FirstOrDefault();
            if (recipe == null)
            {
                return HttpNotFound();
            }
            return View(recipe);
        }

        // POST: Recipies/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Recipe recipe = db.Recipies.Find(id);
            db.Recipies.Remove(recipe);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }


        public async Task PostToTwitterAsync(string textToPost)
        {
            var twitter = new TwitterApi("eJoJ8NmB5DWISWJg9yvxh1S3t", "Mu10ktlqSXopm9d1YbjfPF1yO2M9XiKeJfsM2VoJXARS9BkdLk", "2830649719-9cTqj01zuJr0vDulD33VTwiYloQJ65DXdLOFAUy", "FWTByiaUSzJcB4hjeT150u2pkTvZhp5F990rf6y4RU9bf");
            var response = await twitter.Tweet(textToPost);
            
        }
    }
}

Recepies/Recepies/Views/Recipies/Create.cshtml
@model Recepies.Controllers.RecipiesController.CreateRecipieViewModel

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Recipe</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Recipe.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Recipe.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Recipe.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Recipe.Difficulty, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EnumDropDownListFor(model => model.Recipe.Difficulty, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Recipe.Difficulty, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Recipe.PreparationTimeInMinutes, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Recipe.PreparationTimeInMinutes, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Recipe.PreparationTimeInMinutes, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Recipe.Context, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Recipe.Context, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Recipe.Context, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Recipe.Ingredients, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.ListBoxFor(i => Model.IngredientsIds, ViewBag.Ingredients as MultiSelectList,new { @class = "form-control", multiple = "multiple" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

<script src="~/Scripts/jquery-1.10.2.min.js"></script>
<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>

Recepies/Recepies/Views/Recipies/Delete.cshtml
@model Recepies.Models.Recipe

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Recipe</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Difficulty)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Difficulty)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PreparationTimeInMinutes)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PreparationTimeInMinutes)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.User)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.User.FullName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Context)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Context)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Recepies/Recepies/Views/Recipies/Details.cshtml
@model Recepies.Models.Recipe

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Recipe</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Difficulty)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Difficulty)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PreparationTimeInMinutes)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PreparationTimeInMinutes)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.User)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.User.FullName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Context)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Context)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Ingredients)
        </dt>


        <dd>
            @foreach (var item in Model.Ingredients)
            {
                <span class="ingredient-in-recipie">
                    @Html.DisplayFor(modelItem => item.Name)
                </span>
                <label> </label>
            }
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Recepies/Recepies/Views/Recipies/Edit.cshtml
@model Recepies.Models.Recipe

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Recipe</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Difficulty, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EnumDropDownListFor(model => model.Difficulty, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Difficulty, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PreparationTimeInMinutes, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PreparationTimeInMinutes, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PreparationTimeInMinutes, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.User, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.User.FullName, new { htmlAttributes = new { @class = "form-control", disabled = "disabled"} })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Context, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Context, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Context, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

<script src="~/Scripts/jquery-1.10.2.min.js"></script>
<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>

Recepies/Recepies/Views/Recipies/Index.cshtml
@model IEnumerable<Recepies.Models.Recipe>

@{
    ViewBag.Title = "Index";
}

<h2> check out our recommended recipe for you ! </h2>

<p>
    @Html.ActionLink("Wanna try it?", "Details", new { id = -999 }) &nbsp;
</p>


<h2>All Recipies</h2>

<p>
    @Html.ActionLink("Create New", "Create") &nbsp;
    @Html.ActionLink("Search Recipies", "Search")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Difficulty)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.PreparationTimeInMinutes)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.User)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Context)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Difficulty)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.PreparationTimeInMinutes)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.User.FullName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Context)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.Id }) |
            @Html.ActionLink("Details", "Details", new { id=item.Id }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.Id })
        </td>
    </tr>
}

</table>

Recepies/Recepies/Views/Recipies/Search.cshtml
@model IEnumerable<Recepies.Models.Recipe>

@{
    ViewBag.Title = "Search";
}

<h2>Search</h2>

<div>
    @using (Html.BeginForm("Search", "Recipies", FormMethod.Get))
    {
        <span>Ingredient: </span> @Html.DropDownList("ingredient", ViewBag.Ingredients as SelectList, "")
        <span>User: </span> @Html.TextBox("user")
        <span>Difficulty: </span> @Html.DropDownList("level", new List<SelectListItem> { new SelectListItem { Value = "0" , Text ="Chefs" },
                                 new SelectListItem { Value = "1" , Text ="Hard" },
                                 new SelectListItem { Value = "2" , Text ="Normal" },
                                 new SelectListItem { Value = "3" , Text ="Simple" } }, "")
        <input type="submit" value="Search" />
    }
</div>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Difficulty)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.PreparationTimeInMinutes)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Context)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Difficulty)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.PreparationTimeInMinutes)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Context)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.Id }) |
            @Html.ActionLink("Details", "Details", new { id=item.Id }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.Id })
        </td>
    </tr>
}

</table>