Recepies/Recepies/Models/Ingredient.cs
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace Recepies.Models
{
    public class Ingredient
    {
        public int Id { get; set; }

        [Required(ErrorMessage = "Please enter name")]
        public string Name { get; set; }
        public double Calories { get; set; }
        public double Protein { get; set; }
        public double sugar { get; set; }
        public double Iron { get; set; }
        public virtual ICollection<Recipe> RelatedRecipies{get; set;}
    }
}

Recepies/Recepies/Controllers/IngredientsController.cs
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web.Mvc;
using Recepies.Models;
using DbContext = Recepies.Models.DbContext;
using System.Net.Http;
using Newtonsoft.Json.Linq;

namespace Recepies.Controllers
{
    public class IngredientsController : Controller
    {
        private DbContext db = new DbContext();

        // GET: Ingredients
        public ActionResult Index()
        {
            if (((User)HttpContext.Session["user"]) != null)
            {
                return View(db.Ingredients.ToList());
            }
            return RedirectToAction("Index", "Error");

        }

        // GET: Ingredients/Search
        public ActionResult Search(string caloriesFrom = null, string caloriesTo = null)
        {
            if (((User)HttpContext.Session["user"]) != null)
            {
                var returnDataQurey = db.Ingredients.Select(i => i);

                if (!string.IsNullOrEmpty(caloriesFrom))
                {
                    var caloriesFromNumber = double.Parse(caloriesFrom);
                    returnDataQurey = returnDataQurey.Where(i => i.Calories >= caloriesFromNumber);
                }

                if (!string.IsNullOrEmpty(caloriesTo))
                {
                    var caloriesToNumber = double.Parse(caloriesTo);
                    returnDataQurey = returnDataQurey.Where(i => i.Calories <= caloriesToNumber);
                }

                var result = returnDataQurey.GroupBy(i => i.Calories).ToDictionary(x => x.Key, y => y.ToList());
                return View(result);
            }
            return RedirectToAction("Index", "Error");
        }

        // GET: Ingredients/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return RedirectToAction("Index", "Error");
            }
            Ingredient ingredient = db.Ingredients.Find(id);
            if (ingredient == null)
            {
                return HttpNotFound();
            }
            return View(ingredient);
        }

        // GET: Ingredients/Create
        public ActionResult Create()
        {
            var curUser = ((User)HttpContext.Session["user"]);
            if (curUser != null)
            {
                if (curUser.IsManager)
                {
                    return View();
                }
                else
                {
                    return RedirectToAction("Index", "Error", new { message = "you are not authorized" });
                }
            }
            return RedirectToAction("Index", "Error");
        }

        // POST: Ingredients/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Name")] Ingredient ingredient)
        {
            if (ModelState.IsValid)
            {
                var newIngredient = getIngredientInfo(ingredient);
                db.Ingredients.Add(newIngredient);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(ingredient);
        }

        // GET: Ingredients/Edit/5
        public ActionResult Edit(int? id)
        {
            var curUser = ((User)HttpContext.Session["user"]);
            if (curUser != null)
            {
                if (curUser.IsManager)
                {
                    if (id == null)
                    {
                        return RedirectToAction("Index", "Error");
                    }
                    Ingredient ingredient = db.Ingredients.Find(id);
                    if (ingredient == null)
                    {
                        return HttpNotFound();
                    }
                    return View(ingredient);
                }
                else
                {
                    return RedirectToAction("Index", "Error", new { message = "you are not authorized" });
                }
            }
            else
            {
                return RedirectToAction("Index", "Error");
            }
        }

        // POST: Ingredients/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Name,Calories,Protein,sugar,Iron")] Ingredient ingredient)
        {
            var curUser = ((User)HttpContext.Session["user"]);
            if (curUser != null)
            {
                if (curUser.IsManager)
                {
                    if (ModelState.IsValid)
                    {
                        db.Entry(ingredient).State = EntityState.Modified;
                        db.SaveChanges();
                        return RedirectToAction("Index");
                    }
                    return View(ingredient);
                }
                else
                {
                    return RedirectToAction("Index", "Error", new { message = "you are not authorized" });
                }
            }
            else
            {
                return RedirectToAction("Index", "Error");
            }
        }

        // GET: Ingredients/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return RedirectToAction("Index", "Error");
            }
            Ingredient ingredient = db.Ingredients.Find(id);
            if (ingredient == null)
            {
                return HttpNotFound();
            }
            return View(ingredient);
        }

        // POST: Ingredients/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Ingredient ingredient = db.Ingredients.Find(id);
            try
            {
                db.Ingredients.Remove(ingredient);
                db.SaveChanges();
            }
            catch
            {
                return RedirectToAction("Index", "Error", new { message = "ERROR - You are tring to delete ingredient that is part of one or more recipie" });
            }
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        // This method use the web service to get the calories, iron, protein and sugar of ingredient
        private Ingredient getIngredientInfo(Ingredient indredient)
        {
            using (var client = new HttpClient())
            {
                var response = client.GetAsync(string.Format("https://api.nutritionix.com/v1_1/search/{0}?results=0%3A1&cal_min=0&cal_max=50000&fields=item_name%2Cnf_calories%2Cnf_sugars%2Cnf_protein%2Cnf_iron_dv&appId=70b305ba&appKey=32f30b733ae3f3b3c9727e99a6935fcc", indredient.Name)).Result;
                var result = response.Content.ReadAsStringAsync().Result;
                var data = JObject.Parse(result);
                if (data["hits"].Count() != 0)
                {
                    var fields = data["hits"].First["fields"];
                    indredient.Calories = fields["nf_calories"].Value<double>();
                    indredient.Iron = fields["nf_iron_dv"].Value<double>();
                    indredient.Protein = fields["nf_protein"].Value<double>();
                    indredient.sugar = fields["nf_sugars"].Value<double>();
                }
                return indredient;
            }
        }
    }
}

Recepies/Recepies/Views/Ingredients/Create.cshtml
@model Recepies.Models.Ingredient

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Ingredient</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

<script src="~/Scripts/jquery-1.10.2.min.js"></script>
<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>

Recepies/Recepies/Views/Ingredients/Delete.cshtml
@model Recepies.Models.Ingredient

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Ingredient</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Calories)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Calories)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Protein)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Protein)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.sugar)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.sugar)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Iron)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Iron)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Recepies/Recepies/Views/Ingredients/Details.cshtml
@model Recepies.Models.Ingredient

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Ingredient</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Calories)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Calories)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Protein)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Protein)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.sugar)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.sugar)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Iron)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Iron)
        </dd>

    </dl>
</div>
@{var sessionVar = (Recepies.Models.User)HttpContext.Current.Session["user"];
    if (sessionVar.IsManager)
    {
<p>
   
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |                                                            
    @Html.ActionLink("Back to List", "Index")
</p>
    }
    else
    {
        @Html.ActionLink("Back to List", "Index")
    }
}
 

Recepies/Recepies/Views/Ingredients/Edit.cshtml
@model Recepies.Models.Ingredient

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Ingredient</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Calories, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Calories, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Calories, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Protein, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Protein, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Protein, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.sugar, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.sugar, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.sugar, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Iron, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Iron, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Iron, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

<script src="~/Scripts/jquery-1.10.2.min.js"></script>
<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>

Recepies/Recepies/Views/Ingredients/Index.cshtml
@model IEnumerable<Recepies.Models.Ingredient>

@{
    ViewBag.Title = "Index";
}

<h2>All Ingredients</h2>

<p>
    @{var sessionVar = (Recepies.Models.User)HttpContext.Current.Session["user"];
        if (sessionVar.IsManager)
        {

            @Html.ActionLink("Create New", "Create") <span>&nbsp;</span>
        } }
    @Html.ActionLink("Search Ingredients", "Search")
</p>

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Calories)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Protein)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.sugar)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Iron)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model)
{
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Calories)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Protein)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.sugar)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Iron)
        </td>

            @if (sessionVar.IsManager)
            {
                <td>
                    @Html.ActionLink("Details", "Details", new { id = item.Id }) |
                    @Html.ActionLink("Edit", "Edit", new { id = item.Id }) |
                    @Html.ActionLink("Delete", "Delete", new { id = item.Id })
                </td>
            }
            else
            {
                <td>
                   @Html.ActionLink("Details", "Details", new { id = item.Id }) 
                </td>
            }
</tr>
    }
</table>

Recepies/Recepies/Views/Ingredients/Search.cshtml
@model Dictionary<double, List<Recepies.Models.Ingredient>>

@{
    ViewBag.Title = "Search";
}

<h2>Search</h2>

<div>
    @using (Html.BeginForm("Search", "Ingredients", FormMethod.Get))
    {
        <span>Calories: From </span> @Html.TextBox("caloriesFrom", null, new { @type = "number", step = "0.01" }) <span> To </span> @Html.TextBox("caloriesTo", null, new { @type = "number", step = "0.01" })
        <input type="submit" value="Search" />
    }
</div>
<table class="table">
    @foreach (var item in Model)
    {
        <tr><td></td></tr>
        <tr>
            <td><b>Calories: @Html.DisplayFor(modelItem => item.Key)</b></td>
        </tr>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model[0][0].Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model[0][0].Calories)
            </th>
            <th>
                @Html.DisplayNameFor(model => model[0][0].Protein)
            </th>
            <th>
                @Html.DisplayNameFor(model => model[0][0].sugar)
            </th>
            <th>
                @Html.DisplayNameFor(model => model[0][0].Iron)
            </th>
            <th></th>
        </tr>

        foreach (var indredient in item.Value)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => indredient.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => indredient.Calories)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => indredient.Protein)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => indredient.sugar)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => indredient.Iron)
                </td>
                <td>
                    @Html.ActionLink("Details", "Details", new { id = indredient.Id })

                    @{var sessionVar = (Recepies.Models.User)HttpContext.Current.Session["user"];
                        if (sessionVar.IsManager)
                        {
                            <span>|</span>
                            @Html.ActionLink("Edit", "Edit", new { id = indredient.Id })
                            <span>|</span>
            @Html.ActionLink("Delete", "Delete", new { id = indredient.Id });
                    }}
                </td>
            </tr>
                            }
                        }
</table>